### PR TITLE
Remove payment batching chapter

### PR DESCRIPTION
**Pull request by jnewbery**
It's now been posted as a blog entry at https://bitcoinops.org/en/payment-batching/

### CODE REVIEW

**Comment by jnewbery** [comment]
I assume this won't break anything and we don't have any links pointing to this directory. @harding?

**Comment by harding** [comment]
We have multiple links pointing here from our website, and there may be links pointing here from other people's websites.  We can update our website, of course, but I think it would be best just to turn the deletion of `x.payment_batching/payment_batching.md` into a complete replacement of its content with just something like `[Chapter moved.](https://bitcoinops.org/en/payment-batching/)`.

**Comment by jnewbery** [comment]
> I think it would be best just to turn the deletion of x.payment_batching/payment_batching.md into a complete replacement of its content with just something like [Chapter moved.](https://bitcoinops.org/en/payment-batching/).

Done

> We have multiple links pointing here from our website [...] We can update our website,

I'll open a PR to do that before merging this.

**Comment by harding** [comment]
ACK

**Pull request merged**
